replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"  # or "gce" if using GKE default
  annotations:
    kubernetes.io/ingress.class: "nginx"  # or "gce"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

