replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: microservice.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []  # Add TLS secrets here if using HTTPS

resources: {}
