apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservice-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservice-rb
subjects:
  - kind: ServiceAccount
    name: microservice-sa
roleRef:
  kind: Role
  name: microservice-role
  apiGroup: rbac.authorization.k8s.io
