name: Terraform Deploy to GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Terraform Init/Plan/Apply
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      ZONE: ${{ secrets.GCP_ZONE }}
      BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Authenticate to Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Setup gcloud CLI (optional but useful)
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      # Terraform Setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

